### ISSUE TITLE
question in training

### ISSUE THREAD

**Issue by muses0229** [tiangexiang/OccNeRF#2]

**Comment by yejr0229** [comment]
During training,I encounter this error:
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    main()
  File "train.py", line 43, in main
    train_dataloader=train_loader)
  File "core/train/trainers/occnerf/trainer.py", line 230, in train
    net_output = self.network(**data)
  File "/media/data4/yejr/conda_env/occnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "core/nets/occnerf/network.py", line 636, in forward
    all_ret = self._batchify_rays(packed_ray_infos, **kwargs)
  File "core/nets/occnerf/network.py", line 335, in _batchify_rays
    ret = self._render_rays(rays_flat[i:i+cfg.chunk], **kwargs)
  File "core/nets/occnerf/network.py", line 501, in _render_rays
    non_rigid_pos_embed_fn=non_rigid_pos_embed_fn)
  File "core/nets/occnerf/network.py", line 211, in _query_mlp
    chunk=chunk)
  File "core/nets/occnerf/network.py", line 276, in _apply_mlp_kernals
    slices_y=self.slices_y.to(xyz.device)
TypeError: knn() got an unexpected keyword argument 'ranges_x'

It happends at kpknn:
knn_idxs = kpknn(xyz.repeat(4,1),
                             torch.cat([self.point_base, self.point_base[self.fps_index[0]], self.point_base[self.fps_index[1]], 
                             self.point_base[self.fps_index[2]]], dim=0),
                             k,
                             #distance_limit = 0.1,
                             return_distance = False,
                             padding_mode= "empty",
                             ranges_x=ranges_x.to(xyz.device), 
                             slices_x=self.slices_x.to(xyz.device), 
                             ranges_y=self.ranges_y.to(xyz.device), 
                             slices_y=self.slices_y.to(xyz.device)
                                )

and here is knn's input:
def knn(
    q_points: Tensor,
    s_points: Tensor,
    k: int,
    dilation: int = 1,
    distance_limit: float = None,
    return_distance: bool = False,
    remove_nearest: bool = False,
    transposed: bool = False,
    padding_mode: str = "nearest",
    inf: float = 1e10,
):

I use "https://github.com/qinzheng93/Easy-KPConv.git" you provided to install easy_kpconv,how to deal with it?

**Comment by tiangexiang** [comment]
Hi, thanks for letting me know. I have now refactored the code to remove dependency on easy_kpconv, users are expected to install [pykeops](https://www.kernel-operations.io/keops/python/installation.html) directly. I have also tried to clean the codes to be more organized. Please pull the newly updated repository and try again. Thank you!

**Comment by yejr0229** [comment]
Thanks for replying,and I'd like to know the CUDA version you tested on.My version is torch1.8.1+cu101,and encountered OOM issue during training,at the beginning I installed torch1.8.1+cu111 but it failed when building pytorch3d,I wonder how many memory is needed for occnerf and how to fix this problem?Thanks a lot.

**Comment by yejr0229** [comment]
Thanks for replying,and I wonder can the model train from last checkpoint?

**Comment by tiangexiang** [comment]
Yes! The training can be resumed from the last checkpoint (as in the same experiment), e.g. please run:
`python train.py --cfg configs/occnerf/zju_mocap/387/occnerf.yaml resume True`
to load the last checkpoint and resume training.

**Comment by yejr0229** [comment]
Thanks for replying.Now I have completed the training of the model,then I use this command to render:
python run.py \
    --type movement \
    --cfg configs/occnerf/zju_mocap/387/occnerf.yaml 

and I get the following error:
The rendering is saved in /media/data4/yejr/OCCNeRF/experiments/occnerf/zju_mocap/p387/occnerf/latest/movement
Traceback (most recent call last):
  File "run.py", line 244, in <module>
    globals()[f'run_{args.type}']()
  File "run.py", line 147, in run_movement
    model = load_network(model)
  File "run.py", line 35, in load_network
    model.load_state_dict(ckpt['network'], strict=True)
  File "/media/data4/yejr/conda_env/occnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Network:
        Unexpected key(s) in state_dict: "point_base", "point_dist", "point_counter", "cnl_mlp.module.encoder.embeddings", "cnl_mlp.module.encoder.offsets", "cnl_mlp.module.pts_linears.0.weight", "cnl_mlp.module.pts_linears.0.bias", "cnl_mlp.module.pts_linears.2.weight", "cnl_mlp.module.pts_linears.2.bias", "cnl_mlp.module.pts_linears.4.weight", "cnl_mlp.module.pts_linears.4.bias", "cnl_mlp.module.pts_linears.6.weight", "cnl_mlp.module.pts_linears.6.bias", "cnl_mlp.module.geo_linear.0.weight", "cnl_mlp.module.geo_linear.0.bias", "cnl_mlp.module.rgb_linears.0.weight", "cnl_mlp.module.rgb_linears.0.bias", "cnl_mlp.module.rgb_linears.2.weight", "cnl_mlp.module.rgb_linears.2.bias", "cnl_mlp.module.rgb_linears.4.weight", "cnl_mlp.module.rgb_linears.4.bias", "cnl_mlp.module.rgb_linears.6.weight", "cnl_mlp.module.rgb_linears.6.bias", "cnl_mlp.module.output_linear.0.weight", "cnl_mlp.module.output_linear.0.bias".

Then I try to change model.load_state_dict(ckpt['network'], strict=True) to model.load_state_dict(ckpt['network'], strict=False),and get this error:
load network from  /media/data4/yejr/OCCNeRF/experiments/occnerf/zju_mocap/p387/occnerf/latest.tar
Traceback (most recent call last):
  File "run.py", line 245, in <module>
    globals()[f'run_{args.type}']()
  File "run.py", line 148, in run_movement
    model = load_network(model)
  File "run.py", line 38, in load_network
    return model.cuda().deploy_mlps_to_secondary_gpus()
  File "core/nets/occnerf/network.py", line 147, in deploy_mlps_to_secondary_gpus
    self.cnl_mlp = self.cnl_mlp.to(cfg.secondary_gpus[0])
  File "/media/data4/yejr/conda_env/occnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'Network' object has no attribute 'cnl_mlp'

I'm confused about this,is it due to different pytorch environments?I use torch1.8.1+cu111 following the requirements.txt and use one RTX3090 for training and rendering.

**Comment by tiangexiang** [comment]
Sorry for the problem. It has been fixed in the latest commit. Please pull again and give it a try!

**Comment by yejr0229** [comment]
Thanks for the help,now I have done rendering.I want to compute the psnr between rendered image and GT,I use 
python run.py \
    --type freeview \
    --cfg configs/occnerf/zju_mocap/387/occnerf.yaml \
    freeview.frame_idx 128
to render frame_128 from views without training view,I think I will get (23-1)=22 images,but I get 100 images,so some of these 100 images are virtual cameras which I have no GT to compute psnr,could you please answer this question?

**Comment by tiangexiang** [comment]
To evaluate on certain frame, please use `render_allview.sh` the script, it will render the 23 images wrt to the given camera configurations.

**Comment by yejr0229** [comment]
I use this script and get the following error:
Traceback (most recent call last):
  File "run.py", line 247, in <module>
    globals()[f'run_{args.type}']()
  File "run.py", line 192, in run_allview
    if not cfg.render_folder_name else cfg.render_folder_name)
  File "run.py", line 73, in _freeview
    test_loader = create_dataloader(data_type)
  File "/home/yejr/Digital_Avater/OccNeRF/core/data/create_dataset.py", line 66, in create_dataloader
    dataset = create_dataset(data_type=data_type, evaluate=evaluate)
  File "/home/yejr/Digital_Avater/OccNeRF/core/data/create_dataset.py", line 51, in create_dataset
    dataset = dataset(**args)
  File "core/data/occnerf/allview.py", line 56, in __init__
    cameras = self.load_train_cameras()
  File "core/data/occnerf/allview.py", line 94, in load_train_cameras
    with open(os.path.join(self.dataset_path, 'all_cameras.pkl'), 'rb') as f: 
FileNotFoundError: [Errno 2] No such file or directory: '/media/data4/yejr/OCCNeRF/dataset/zju_mocap/387/all_cameras.pkl'
Is the missing file 'all_cameras.pkl' the same as  'cameras.pkl' in the dataset?

**Comment by yejr0229** [comment]
I also have some questions about the evaluation metrics.Can you provide more details about PSNR_vis and PSNR_full?As I know,PSNR_vis only compute two images on pixels non-zero,and PSNR_full compute two images on people's mask region.

**Comment by tiangexiang** [comment]
Sorry for the late response and yes you are correct! Note that in the main paper we didn't report PSNR_body and SSIM_body, feel free to add those results if you find useful :)

**Comment by yejr0229** [comment]
Thanks for replying.In oreder to compare with occnerf with other method,I have tried to modify the training setting about occnerf,I set training view to 4,and sample one image every 5 frames for a total of 100 images for training.The results I get are far from your original version.Why did the result drop so baddly?
![camera_01_frame_000030](https://github.com/tiangexiang/OccNeRF/assets/132911839/3b8fd160-67e5-4ee6-a93f-fdfb8d8e0d48)

**Comment by tiangexiang** [comment]
Have you recalculated the mask ratio and update the masking configures accordingly? The default masking configure is computed based on the default view and all frames. It is very likely the 100 images from view 4 may be mostly masked (leading to bad results) if you are still using the default masking configures. Please check the masking first!

**Comment by yejr0229** [comment]
Thanks for reminding me!Now I only want to change the training view from [0] to [4] and still use 570 images for training.I wonder should I change the occlusion_mid and occlusion_width since the position of people may be differ from view [0]?In view [0],you set occlusion_mid=460 and occlusion_width=70.Also for the rest subjects,is doing this necessary?

**Comment by tiangexiang** [comment]
Yes, we basically decide `occlusion_mid` first based on the average width of visible human masks in all frames, then decide `occlusion_width` via binary search to make sure a certain portion of human body will be masked. This process has to be repeated for all *NEW* videos, include new subjects, new view etc...

**Comment by yejr0229** [comment]
I see.And can you please provide the code for the above steps?
