### ISSUE TITLE
Question about multi-gpu training

### ISSUE THREAD

**Issue by imabackstabber** [tiangexiang/OccNeRF#4]
Hi, I've been training my own model using current code. It works well when only one gpu (single gpu) is available, but when I set `CUDA_VISIBLE_DEVICES=0,1` (2 gpus available now), it crashes and reports:
```
************************************                                                                                                    
Traceback (most recent call last):                                                                                                      
  File "/data/wendiyang/git_repo/OccNeRF/train.py", line 49, in <module>                                                                
    main()                                                                                                                              
  File "/data/wendiyang/git_repo/OccNeRF/train.py", line 42, in main                                                                    
    trainer.train(epoch=epoch,                                                                                                          
  File "core/train/trainers/occnerf/trainer.py", line 238, in train                                                                     
    net_output = self.network(**data)                                                                                                   
  File "/data/wendiyang/anaconda3/envs/occnerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl        
    return forward_call(*input, **kwargs)                                                                                               
  File "core/nets/occnerf/network.py", line 616, in forward                                                                             
    all_ret = self._batchify_rays(packed_ray_infos, **kwargs)                                                                           
  File "core/nets/occnerf/network.py", line 311, in _batchify_rays                                                                      
    ret = self._render_rays(rays_flat[i:i+cfg.chunk], **kwargs)                                                                         
  File "core/nets/occnerf/network.py", line 472, in _render_rays                                                                        
    query_result = self._query_mlp(                                                                                                     
  File "core/nets/occnerf/network.py", line 177, in _query_mlp                                                                          
    result = self._apply_mlp_kernals(                                                                                                   
  File "core/nets/occnerf/network.py", line 240, in _apply_mlp_kernals                                                                  
    knn_idxs = fast_knn(xyz.repeat(4,1),                                                                                                
  File "/data/wendiyang/git_repo/OccNeRF/core/nets/occnerf/knn.py", line 150, in knn                                                    
    knn_distances, knn_indices = keops_knn(q_points, s_points, final_k, ranges_x, slices_x, ranges_y, slices_y)  # (*, N, k)            
  File "/data/wendiyang/git_repo/OccNeRF/core/nets/occnerf/knn.py", line 83, in keops_knn                                               
    _, knn_indices = dij.Kmin_argKmin(k, dim=num_batch_dims + 1)                                                                        
  File "/data/wendiyang/anaconda3/envs/occnerf/lib/python3.9/site-packages/pykeops/common/lazy_tensor.py", line 2265, in Kmin_argKmin   
    return self.reduction("KMin_ArgKMin", opt_arg=K, axis=axis, dim=dim, **kwargs)                                                      
  File "/data/wendiyang/anaconda3/envs/occnerf/lib/python3.9/site-packages/pykeops/common/lazy_tensor.py", line 769, in reduction       
    return res()                                                                                                                        
  File "/data/wendiyang/anaconda3/envs/occnerf/lib/python3.9/site-packages/pykeops/common/lazy_tensor.py", line 951, in __call__        
    return self.callfun(*args, *self.variables, **self.kwargs)                                                                          
  File "/data/wendiyang/anaconda3/envs/occnerf/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 626, in __call__ 
    out = GenredAutograd.apply(                                                                                                         
  File "/data/wendiyang/anaconda3/envs/occnerf/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 59, in forward   
    raise ValueError(                                                                                                                   
ValueError: [KeOps] Input arrays must be all located on the same device.  
```
It seems something goes wrong with KeOps when training with multi-gpus. Any suggestions? @tiangexiang

**Comment by tiangexiang** [comment]
Hi, thanks for your interest. Unfortunately, all the experiments were executed on a single GPU, so I am afraid I won't be able to provide any updates to cater for multi-gpus. 
Since the problem is from KeOps, which is only used to compute KNN efficiently, walkarounds include using other KNN computing packages instead of KeOps. 
In this [draft script](https://github.com/tiangexiang/OccNeRF/blob/main/test_knn.py), multiple KNN compute methods are benchmarked. You may want to use the script to find a method that fits your situation the best. My personal recommendation would be ball query in pytorch3d, since no additional package is required in this way.

**Comment by imabackstabber** [comment]
I know, thanks for your reply.
